# Generated by Django 5.1.15 on 2026-03-19 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='目的地名称')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='省份/直辖市')),
                ('destination_type', models.CharField(choices=[('city', '城市'), ('region', '区域'), ('scenic', '景区')], default='city', max_length=20, verbose_name='目的地类型')),
                ('short_intro', models.CharField(blank=True, max_length=220, verbose_name='短介绍')),
                ('overview', models.TextField(blank=True, verbose_name='概述')),
                ('travel_highlights', models.TextField(blank=True, verbose_name='玩法亮点')),
                ('cover_image', models.URLField(blank=True, verbose_name='封面图')),
                ('best_season', models.CharField(blank=True, max_length=200, verbose_name='推荐季节')),
                ('recommended_days', models.PositiveIntegerField(default=2, verbose_name='建议游玩天数')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='平均评分')),
                ('average_ticket', models.CharField(blank=True, max_length=255, verbose_name='门票参考')),
                ('attraction_count', models.PositiveIntegerField(default=0, verbose_name='景点数量')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('travel_tips', models.TextField(blank=True, verbose_name='出行建议')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='来源文件')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-average_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='景点名称')),
                ('source_url', models.URLField(blank=True, verbose_name='来源链接')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('description', models.TextField(blank=True, verbose_name='介绍')),
                ('opening_hours', models.TextField(blank=True, verbose_name='开放时间')),
                ('image_url', models.URLField(blank=True, verbose_name='图片链接')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='评分')),
                ('suggested_play_time', models.CharField(blank=True, max_length=120, verbose_name='建议游玩时间')),
                ('best_season', models.CharField(blank=True, max_length=255, verbose_name='建议季节')),
                ('ticket_info', models.TextField(blank=True, verbose_name='门票')),
                ('tips', models.TextField(blank=True, verbose_name='小贴士')),
                ('source_page', models.PositiveIntegerField(default=1, verbose_name='来源页码')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='景点标签')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='来源文件')),
                ('imported_from_excel', models.BooleanField(default=False, verbose_name='来自 Excel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='core.travelcity')),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='方案标题')),
                ('departure_city', models.CharField(blank=True, max_length=100, verbose_name='出发城市')),
                ('duration_days', models.PositiveIntegerField(default=3, verbose_name='出行天数')),
                ('budget_level', models.CharField(default='balanced', max_length=50, verbose_name='预算档位')),
                ('companions', models.CharField(default='双人', max_length=60, verbose_name='同行方式')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='兴趣偏好')),
                ('summary', models.TextField(blank=True, verbose_name='方案摘要')),
                ('estimated_budget', models.PositiveIntegerField(default=0, verbose_name='预算估算')),
                ('itinerary', models.JSONField(blank=True, default=list, verbose_name='行程内容')),
                ('status', models.CharField(choices=[('generated', '已生成'), ('collected', '已收藏'), ('completed', '已完成')], default='generated', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to='core.travelcity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('cover_image', models.URLField(blank=True, verbose_name='封面图')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='published', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.attraction')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_posts', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.travelcity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.travelpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.travelpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像链接')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('home_city', models.CharField(blank=True, max_length=100, verbose_name='常住城市')),
                ('favorite_styles', models.JSONField(blank=True, default=list, verbose_name='偏好风格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='attraction',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='uniq_attraction_city_name'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_like'),
        ),
    ]
