# Generated by Django 5.1.15 on 2026-03-20 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_travelcity_attraction_travelplan_travelpost_postlike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, verbose_name='分类')),
                ('action', models.CharField(max_length=80, verbose_name='操作')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('target_type', models.CharField(blank=True, max_length=80, verbose_name='对象类型')),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='对象 ID')),
                ('target_name', models.CharField(blank=True, max_length=255, verbose_name='对象名称')),
                ('request_path', models.CharField(blank=True, max_length=255, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, max_length=12, verbose_name='请求方法')),
                ('ip_address', models.CharField(blank=True, max_length=64, verbose_name='IP 地址')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
