# Generated by Django 5.1.15 on 2026-03-21 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sync_profile_home_city(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    TravelCity = apps.get_model('core', 'TravelCity')

    city_name_map = {city.name: city.id for city in TravelCity.objects.all()}
    for profile in UserProfile.objects.exclude(home_city=''):
        city_id = city_name_map.get(profile.home_city)
        if not city_id:
            continue
        profile.home_city_ref_id = city_id
        profile.save(update_fields=['home_city_ref'])


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profiles', to='core.travelcity'),
        ),
        migrations.RunPython(sync_profile_home_city, noop),
        migrations.CreateModel(
            name='PostFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.travelpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_favorite')],
            },
        ),
    ]
