# Generated by Django 5.1.15 on 2026-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_home_city_ref_postfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='travelcity',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='头像链接'),
        ),
    ]
