# Generated by Django 5.1.15 on 2026-03-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_travelmapcache_travelcitygeocache"),
    ]

    operations = []
