# Generated by Django 5.1.15 on 2026-03-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attraction_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCityGeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=64)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('adcode', models.CharField(blank=True, max_length=20)),
                ('citycode', models.CharField(blank=True, max_length=20)),
                ('city_name', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('formatted_address', models.CharField(blank=True, max_length=255)),
                ('source_provider', models.CharField(default='amap', max_length=32)),
                ('source_signature', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_cache', to='core.travelcity')),
            ],
            options={
                'ordering': ['city_id'],
            },
        ),
    ]
